ERROR:root:Exception occured in updown
Traceback (most recent call last):
  File "D:\ViteosModel2.0\125_Weiss_Production_loop_1_argument_3.py", line 2441, in <module>
    for d in tqdm(k1):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1003, in __init__
    self.display()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1397, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 304, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 297, in fp_write
    fp.write(_unicode(s))
AttributeError: 'NoneType' object has no attribute 'write'
ERROR:root:Exception occured
Traceback (most recent call last):
  File "D:\ViteosModel2.0\125_Weiss_Production_loop_1_argument_3.py", line 2655, in <module>
    for d in tqdm(aa_new['Date'].unique()):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1003, in __init__
    self.display()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1397, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 304, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 297, in fp_write
    fp.write(_unicode(s))
AttributeError: 'NoneType' object has no attribute 'write'
